[package]
authors = ["Andy Lok <andylokandy@hotmail.com>"]
edition = "2018"
name = "tikv-client"
version = "0.1.8"

[dependencies]
futures = "0.3"
lazy_static = "1"
pyo3 = { version="0.13.2", features=["extension-module"] }
tikv-client = { git="https://github.com/tikv/client-rust.git", branch="master" }
tokio = { version="1.7.1", features=["rt-multi-thread", "sync"] }

[lib]
crate-type = ["cdylib"]
name = "tikv_client"
